[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.lint]
command = "cargo"
args = ["clippy", "--all-targets", "--all-features"]

[tasks.install-targets]
script = [
  "rustup target add x86_64-apple-darwin",
  "rustup target add aarch64-apple-darwin",
  "rustup target add armv7-unknown-linux-gnueabihf",
  "rustup target add aarch64-unknown-linux-gnu",
  "rustup target add aarch64-unknown-linux-musl",
  "rustup target add x86_64-unknown-linux-gnu",
  "rustup target add x86_64-unknown-linux-musl",
  "rustup target add aarch64-pc-windows-msvc",
  "rustup target add i686-pc-windows-msvc",
  "rustup target add x86_64-pc-windows-msvc",
]

[tasks.release]
dependencies = ["install-targets"]
run_task = [
  { name = "release-x86_64-apple-darwin" },
  { name = "release-aarch64-apple-darwin" },
  { name = "release-armv7-unknown-linux-gnueabihf" },
  { name = "release-aarch64-unknown-linux-gnu" },
  { name = "release-aarch64-unknown-linux-musl" },
  { name = "release-x86_64-unknown-linux-gnu" },
  { name = "release-x86_64-unknown-linux-musl" },
  { name = "release-aarch64-pc-windows-msvc" },
  { name = "release-i686-pc-windows-msvc" },
  { name = "release-x86_64-pc-windows-msvc" },
]
# parallel = true

[tasks.release-x86_64-apple-darwin]
command = "cargo"
args = ["zigbuild", "--release", "--target=x86_64-apple-darwin"]

[tasks.release-aarch64-apple-darwin]
command = "cargo"
args = ["zigbuild", "--release", "--target=aarch64-apple-darwin"]

[tasks.release-armv7-unknown-linux-gnueabihf]
command = "cargo"
args = ["zigbuild", "--release", "--target=armv7-unknown-linux-gnueabihf"]

[tasks.release-aarch64-unknown-linux-gnu]
command = "cargo"
args = ["zigbuild", "--release", "--target=aarch64-unknown-linux-gnu"]

[tasks.release-aarch64-unknown-linux-musl]
command = "cargo"
args = ["zigbuild", "--release", "--target=aarch64-unknown-linux-musl"]

[tasks.release-x86_64-unknown-linux-gnu]
command = "cargo"
args = ["zigbuild", "--release", "--target=x86_64-unknown-linux-gnu"]

[tasks.release-x86_64-unknown-linux-musl]
command = "cargo"
args = ["zigbuild", "--release", "--target=x86_64-unknown-linux-musl"]

[tasks.release-aarch64-pc-windows-msvc]
command = "cargo"
args = ["zigbuild", "--release", "--target=aarch64-pc-windows-msvc"]

[tasks.release-i686-pc-windows-msvc]
command = "cargo"
args = ["zigbuild", "--release", "--target=i686-pc-windows-msvc"]

[tasks.release-x86_64-pc-windows-msvc]
command = "cargo"
args = ["zigbuild", "--release", "--target=x86_64-pc-windows-msvc"]
